ALTER TABLE pasien
  ADD COLUMN IF NOT EXISTS telepon VARCHAR(20),
  ADD COLUMN IF NOT EXISTS email VARCHAR(100),
  ADD COLUMN IF NOT EXISTS alamat TEXT,
  ADD COLUMN IF NOT EXISTS golongan_darah VARCHAR(5),
  ADD COLUMN IF NOT EXISTS tinggi_badan VARCHAR(10),
  ADD COLUMN IF NOT EXISTS berat_badan VARCHAR(10),
  ADD COLUMN IF NOT EXISTS alergi TEXT,
  ADD COLUMN IF NOT EXISTS no_asuransi VARCHAR(50);
